site_name: TehTalkJohn
site_description: TecTalk
site_url: https://github.com/JohnTelford/techtalkjohn-2

theme:
  name: material
 
plugins:
- search
- blog:
    archive_date_format: MMMM 校校校校
    categories_allowed:
        - Article
