site_name: TehTalkJohn
site_description: TecTalk
site_url: https://github.com/JohnTelford/techtalkjohn-2

theme:
  name: material
  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16

# features:
#     - navigation.instant

# #     - navigation.indexes

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - blog:
      blog_dir: "{blog}/articles"
      blog_toc: true
      archive_date_format: medium
      archive_toc: true
      post_url_date_format: yyyy/MM/dd
      post_excerpt_max_categories: 1
      archive_date_format: MMMM yyyy

      # Blog categories
      categories: true
      categories_allowed:
        - Install
        - Deploy
        - Tools
        - Cattest
      categories_toc: true
      categories_name: "Blog Topics"
      categories_pagination: true
      categories_pagination_per_page: 5
nav:
  - Home: index.md
  - Blog:
      - blog/index.md

copyright: Copyright &copy; 2024 - John M. Telford